In [1]:
import torch

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [2]:
x = torch.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [3]:
print(x.shape)

torch.Size([2, 5])


In [4]:
y = torch.rand([2,5])
print(y)

tensor([[0.4912, 0.7544, 0.7546, 0.0202, 0.5470],
        [0.4355, 0.7089, 0.0033, 0.8497, 0.5726]])


use .view() to reshape, [1, /size/] to flatten

In [5]:
y.view([1,10])

tensor([[0.4912, 0.7544, 0.7546, 0.0202, 0.5470, 0.4355, 0.7089, 0.0033, 0.8497,
         0.5726]])

In [6]:
y = y.view([1,10])

In [7]:
y

tensor([[0.4912, 0.7544, 0.7546, 0.0202, 0.5470, 0.4355, 0.7089, 0.0033, 0.8497,
         0.5726]])